-- Salles et Amphitheatres
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A01', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A02', 50, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A03', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A04', 60, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A05', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A06', 50, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A07', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A08', 40, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A09', 60, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A10', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A11', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A12', 50, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A13', 60, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A14', 30, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle A15', 50, 20, 'salle', 'Bâtiment A', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi A1', 200, 20, 'amphitheatre', 'Bâtiment A', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi A2', 200, 20, 'amphitheatre', 'Bâtiment A', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi A3', 250, 20, 'amphitheatre', 'Bâtiment A', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B01', 50, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B02', 30, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B03', 60, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B04', 50, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B05', 60, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B06', 30, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B07', 30, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B08', 60, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B09', 50, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B10', 40, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B11', 30, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B12', 60, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B13', 60, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B14', 40, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle B15', 30, 20, 'salle', 'Bâtiment B', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi B1', 250, 20, 'amphitheatre', 'Bâtiment B', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi B2', 200, 20, 'amphitheatre', 'Bâtiment B', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi B3', 200, 20, 'amphitheatre', 'Bâtiment B', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C01', 50, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C02', 60, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C03', 60, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C04', 50, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C05', 50, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C06', 60, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C07', 40, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C08', 60, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C09', 40, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C10', 30, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C11', 30, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C12', 30, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C13', 50, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C14', 30, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle C15', 50, 20, 'salle', 'Bâtiment C', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi C1', 200, 20, 'amphitheatre', 'Bâtiment C', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi C2', 200, 20, 'amphitheatre', 'Bâtiment C', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi C3', 250, 20, 'amphitheatre', 'Bâtiment C', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D01', 60, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D02', 30, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D03', 50, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D04', 30, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D05', 50, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D06', 30, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D07', 30, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D08', 60, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D09', 50, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D10', 60, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D11', 30, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D12', 30, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D13', 50, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D14', 50, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle D15', 40, 20, 'salle', 'Bâtiment D', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi D1', 150, 20, 'amphitheatre', 'Bâtiment D', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi D2', 250, 20, 'amphitheatre', 'Bâtiment D', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi D3', 100, 20, 'amphitheatre', 'Bâtiment D', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E01', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E02', 60, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E03', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E04', 30, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E05', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E06', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E07', 50, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E08', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E09', 30, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E10', 30, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E11', 60, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E12', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E13', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E14', 50, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle E15', 40, 20, 'salle', 'Bâtiment E', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi E1', 300, 20, 'amphitheatre', 'Bâtiment E', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi E2', 200, 20, 'amphitheatre', 'Bâtiment E', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi E3', 200, 20, 'amphitheatre', 'Bâtiment E', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F01', 50, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F02', 50, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F03', 60, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F04', 40, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F05', 30, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F06', 50, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F07', 60, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F08', 50, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F09', 40, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F10', 30, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F11', 30, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F12', 60, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F13', 30, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F14', 30, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle F15', 40, 20, 'salle', 'Bâtiment F', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi F1', 300, 20, 'amphitheatre', 'Bâtiment F', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi F2', 200, 20, 'amphitheatre', 'Bâtiment F', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi F3', 250, 20, 'amphitheatre', 'Bâtiment F', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G01', 60, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G02', 40, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G03', 30, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G04', 50, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G05', 50, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G06', 40, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G07', 50, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G08', 50, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G09', 60, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G10', 30, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G11', 60, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G12', 60, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G13', 50, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G14', 30, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Salle G15', 40, 20, 'salle', 'Bâtiment G', ARRAY['tableau', 'projecteur']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi G1', 150, 20, 'amphitheatre', 'Bâtiment G', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi G2', 300, 20, 'amphitheatre', 'Bâtiment G', ARRAY['tableau', 'projecteur', 'micro', 'video']);
INSERT INTO lieu_examen (nom, capacite, capacite_examen, type, batiment, equipements) VALUES ('Amphi G3', 100, 20, 'amphitheatre', 'Bâtiment G', ARRAY['tableau', 'projecteur', 'micro', 'video']);
