-- Formations
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Génie Logiciel', 'FORM-001', 1, 'L1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Génie Logiciel', 'FORM-002', 1, 'L2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Génie Logiciel', 'FORM-003', 1, 'L3', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Génie Logiciel', 'FORM-004', 1, 'M1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Génie Logiciel', 'FORM-005', 1, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Réseaux et Sécurité', 'FORM-006', 1, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Réseaux et Sécurité', 'FORM-007', 1, 'L2', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Réseaux et Sécurité', 'FORM-008', 1, 'L3', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Réseaux et Sécurité', 'FORM-009', 1, 'M1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Réseaux et Sécurité', 'FORM-010', 1, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Intelligence Artificielle', 'FORM-011', 1, 'L1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Intelligence Artificielle', 'FORM-012', 1, 'L2', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Intelligence Artificielle', 'FORM-013', 1, 'L3', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Intelligence Artificielle', 'FORM-014', 1, 'M1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Intelligence Artificielle', 'FORM-015', 1, 'M2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Systèmes Embarqués', 'FORM-016', 1, 'L1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Systèmes Embarqués', 'FORM-017', 1, 'L2', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Systèmes Embarqués', 'FORM-018', 1, 'L3', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Systèmes Embarqués', 'FORM-019', 1, 'M1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Systèmes Embarqués', 'FORM-020', 1, 'M2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Mathématiques Appliquées', 'FORM-021', 2, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Mathématiques Appliquées', 'FORM-022', 2, 'L2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Mathématiques Appliquées', 'FORM-023', 2, 'L3', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Mathématiques Appliquées', 'FORM-024', 2, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Mathématiques Appliquées', 'FORM-025', 2, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Mathématiques Fondamentales', 'FORM-026', 2, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Mathématiques Fondamentales', 'FORM-027', 2, 'L2', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Mathématiques Fondamentales', 'FORM-028', 2, 'L3', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Mathématiques Fondamentales', 'FORM-029', 2, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Mathématiques Fondamentales', 'FORM-030', 2, 'M2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Statistiques', 'FORM-031', 2, 'L1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Statistiques', 'FORM-032', 2, 'L2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Statistiques', 'FORM-033', 2, 'L3', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Statistiques', 'FORM-034', 2, 'M1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Statistiques', 'FORM-035', 2, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Physique Théorique', 'FORM-036', 3, 'L1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Physique Théorique', 'FORM-037', 3, 'L2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Physique Théorique', 'FORM-038', 3, 'L3', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Physique Théorique', 'FORM-039', 3, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Physique Théorique', 'FORM-040', 3, 'M2', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Physique Appliquée', 'FORM-041', 3, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Physique Appliquée', 'FORM-042', 3, 'L2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Physique Appliquée', 'FORM-043', 3, 'L3', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Physique Appliquée', 'FORM-044', 3, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Physique Appliquée', 'FORM-045', 3, 'M2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Astrophysique', 'FORM-046', 3, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Astrophysique', 'FORM-047', 3, 'L2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Astrophysique', 'FORM-048', 3, 'L3', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Astrophysique', 'FORM-049', 3, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Astrophysique', 'FORM-050', 3, 'M2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Chimie Organique', 'FORM-051', 4, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Chimie Organique', 'FORM-052', 4, 'L2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Chimie Organique', 'FORM-053', 4, 'L3', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Chimie Organique', 'FORM-054', 4, 'M1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Chimie Organique', 'FORM-055', 4, 'M2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Chimie Analytique', 'FORM-056', 4, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Chimie Analytique', 'FORM-057', 4, 'L2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Chimie Analytique', 'FORM-058', 4, 'L3', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Chimie Analytique', 'FORM-059', 4, 'M1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Chimie Analytique', 'FORM-060', 4, 'M2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Chimie Industrielle', 'FORM-061', 4, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Chimie Industrielle', 'FORM-062', 4, 'L2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Chimie Industrielle', 'FORM-063', 4, 'L3', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Chimie Industrielle', 'FORM-064', 4, 'M1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Chimie Industrielle', 'FORM-065', 4, 'M2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Biologie Moléculaire', 'FORM-066', 5, 'L1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Biologie Moléculaire', 'FORM-067', 5, 'L2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Biologie Moléculaire', 'FORM-068', 5, 'L3', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Biologie Moléculaire', 'FORM-069', 5, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Biologie Moléculaire', 'FORM-070', 5, 'M2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Écologie', 'FORM-071', 5, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Écologie', 'FORM-072', 5, 'L2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Écologie', 'FORM-073', 5, 'L3', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Écologie', 'FORM-074', 5, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Écologie', 'FORM-075', 5, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Biotechnologie', 'FORM-076', 5, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Biotechnologie', 'FORM-077', 5, 'L2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Biotechnologie', 'FORM-078', 5, 'L3', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Biotechnologie', 'FORM-079', 5, 'M1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Biotechnologie', 'FORM-080', 5, 'M2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Économie et Gestion', 'FORM-081', 6, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Économie et Gestion', 'FORM-082', 6, 'L2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Économie et Gestion', 'FORM-083', 6, 'L3', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Économie et Gestion', 'FORM-084', 6, 'M1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Économie et Gestion', 'FORM-085', 6, 'M2', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Finance', 'FORM-086', 6, 'L1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Finance', 'FORM-087', 6, 'L2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Finance', 'FORM-088', 6, 'L3', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Finance', 'FORM-089', 6, 'M1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Finance', 'FORM-090', 6, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Management', 'FORM-091', 6, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Management', 'FORM-092', 6, 'L2', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Management', 'FORM-093', 6, 'L3', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Management', 'FORM-094', 6, 'M1', 12);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Management', 'FORM-095', 6, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Littérature Française', 'FORM-096', 7, 'L1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Littérature Française', 'FORM-097', 7, 'L2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Littérature Française', 'FORM-098', 7, 'L3', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Littérature Française', 'FORM-099', 7, 'M1', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Littérature Française', 'FORM-100', 7, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Langues Étrangères', 'FORM-101', 7, 'L1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Langues Étrangères', 'FORM-102', 7, 'L2', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Langues Étrangères', 'FORM-103', 7, 'L3', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Langues Étrangères', 'FORM-104', 7, 'M1', 9);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Langues Étrangères', 'FORM-105', 7, 'M2', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L1 Sciences Humaines', 'FORM-106', 7, 'L1', 10);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L2 Sciences Humaines', 'FORM-107', 7, 'L2', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('L3 Sciences Humaines', 'FORM-108', 7, 'L3', 11);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M1 Sciences Humaines', 'FORM-109', 7, 'M1', 8);
INSERT INTO formations (nom, code, dept_id, niveau, nb_modules) VALUES ('M2 Sciences Humaines', 'FORM-110', 7, 'M2', 11);
