-- Professeurs
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gimenez', 'Maggie', 'maggie.gimenez.1@university.edu', 1, 'conseiller en insertion sociale et professionnelle', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Ramos', 'Martin', 'martin.ramos.2@university.edu', 1, 'technicien d''essais', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fontaine', 'Nath', 'nath.fontaine.3@university.edu', 1, 'commissaire de police', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schneider', 'Jacqueline', 'jacqueline.schneider.4@university.edu', 1, 'mécanicien-réparateur en matériel agricole', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Allain', 'Christophe', 'christophe.allain.5@university.edu', 1, 'assistant maternel maternelle', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Moulin', 'Benjamin', 'benjamin.moulin.6@university.edu', 1, 'ajusteur-monteur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lebreton', 'Anne', 'anne.lebreton.7@university.edu', 1, 'traducteur-interprète', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Moulin', 'Michelle', 'michelle.moulin.8@university.edu', 1, 'reporter-photographe', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lévy', 'Paul', 'paul.lévy.9@university.edu', 1, 'militaire technicien de l''air (MTA)', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Robert', 'Suzanne', 'suzanne.robert.10@university.edu', 1, 'courtier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lefort', 'Georges', 'georges.lefort.11@university.edu', 1, 'ingénieur de recherche (papiers cartons)', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamel', 'Marthe', 'marthe.hamel.12@university.edu', 1, 'BIM manager', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('David', 'Nicole', 'nicole.david.13@university.edu', 1, 'vendeur conseil caviste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dupont', 'Eugène', 'eugène.dupont.14@university.edu', 1, 'contrôleur aérien aérienne', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bodin', 'Océane', 'océane.bodin.15@university.edu', 1, 'ingénieur pétrolier pétrolière', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Diallo', 'Cécile', 'cécile.diallo.16@university.edu', 1, 'concepteur-rédacteur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rossi', 'Olivier', 'olivier.rossi.17@university.edu', 1, 'monteur en installations thermiques et climatiques', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mace', 'Dominique', 'dominique.mace.18@university.edu', 1, 'responsable de fabrication en chimie', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Laporte', 'Alex', 'alex.laporte.19@university.edu', 1, 'employé de chai', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dumont', 'Dorothée', 'dorothée.dumont.20@university.edu', 1, 'professeur d''éducation physique et sportive (EPS)', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gros', 'Agnès', 'agnès.gros.21@university.edu', 2, 'conseiller principal d''éducation principale d''éducation', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Perrot', 'Gabriel', 'gabriel.perrot.22@university.edu', 2, 'orthodontiste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dos Santos', 'Gilbert', 'gilbert.dos santos.23@university.edu', 2, 'agent de développement touristique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Legendre', 'Arnaude', 'arnaude.legendre.24@university.edu', 2, 'officier de l''armée de terre', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Étienne', 'Arnaude', 'arnaude.étienne.25@university.edu', 2, 'ingénieur production en mécanique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bonnet', 'Patricia', 'patricia.bonnet.26@university.edu', 2, 'éditeur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Boyer', 'Josette', 'josette.boyer.27@university.edu', 2, 'chef de fabrication des industries graphiques', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chartier', 'Alexandria', 'alexandria.chartier.28@university.edu', 2, 'caissier', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Blondel', 'Patricia', 'patricia.blondel.29@university.edu', 2, 'poissonnier', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Menard', 'Margaux', 'margaux.menard.30@university.edu', 2, 'animateur de radio et de télévision', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Durand', 'Xavier', 'xavier.durand.31@university.edu', 2, 'pédologue', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lopez', 'Lorraine', 'lorraine.lopez.32@university.edu', 2, 'esthéticien-cosméticien', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lambert', 'Dominique', 'dominique.lambert.33@university.edu', 2, 'chirurgien', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pereira', 'David', 'david.pereira.34@university.edu', 2, 'chef monteur monteuse', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Richard', 'Agathe', 'agathe.richard.35@university.edu', 2, 'démographe', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pineau', 'Charles', 'charles.pineau.36@university.edu', 2, 'conseiller d''élevage', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mercier', 'Théodore', 'théodore.mercier.37@university.edu', 2, 'staffeur-ornemaniste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Roussel', 'Roland', 'roland.roussel.38@university.edu', 2, 'vendeur en magasin', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Sanchez', 'Frédérique', 'frédérique.sanchez.39@university.edu', 2, 'géologue modélisateur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Jacques', 'Laurent', 'laurent.jacques.40@university.edu', 2, 'technicien packaging', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Faure', 'Amélie', 'amélie.faure.41@university.edu', 2, 'chargé d''études économiques', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gomes', 'Claudine', 'claudine.gomes.42@university.edu', 2, 'bijoutier-joaillier', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hubert', 'Alphonse', 'alphonse.hubert.43@university.edu', 2, 'puériculteur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Louis', 'Patricia', 'patricia.louis.44@university.edu', 2, 'chargé d''études ressources humaines', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chevallier', 'Marcel', 'marcel.chevallier.45@university.edu', 2, 'attaché d''administration', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dias', 'Diane', 'diane.dias.46@university.edu', 3, 'responsable d''élevage agricole', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Barthelemy', 'Anouk', 'anouk.barthelemy.47@university.edu', 3, 'designer d''interaction', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rossi', 'Maryse', 'maryse.rossi.48@university.edu', 3, 'charpentier métallique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fernandez', 'Xavier', 'xavier.fernandez.49@university.edu', 3, 'chercheur en biologie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Martin', 'Thibault', 'thibault.martin.50@university.edu', 3, 'écrivain', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bailly', 'Benjamin', 'benjamin.bailly.51@university.edu', 3, 'assistant maternel maternelle', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lebreton', 'Laure', 'laure.lebreton.52@university.edu', 3, 'iconographe', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Payet', 'Martine', 'martine.payet.53@university.edu', 3, 'professeur dans l''enseignement agricole', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Couturier', 'Éric', 'éric.couturier.54@university.edu', 3, 'ingénieur électronicien électronicienne', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Valentin', 'Paul', 'paul.valentin.55@university.edu', 3, 'technicien en traitement des matériaux', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Valette', 'Louis', 'louis.valette.56@university.edu', 3, 'responsable de laboratoire de contrôle en biologie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lecoq', 'Richard', 'richard.lecoq.57@university.edu', 3, 'technicien céramiste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hoareau', 'Claire', 'claire.hoareau.58@university.edu', 3, 'animateur de bassin versant', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gomes', 'Roland', 'roland.gomes.59@university.edu', 3, 'juge des enfants', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Weber', 'Gérard', 'gérard.weber.60@university.edu', 3, 'ingénieur qualité moteur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Clément', 'Paulette', 'paulette.clément.61@university.edu', 3, 'directeur artistique', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chrétien', 'Philippine', 'philippine.chrétien.62@university.edu', 3, 'cadreur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Renaud', 'Emmanuelle', 'emmanuelle.renaud.63@university.edu', 3, 'critique d''art', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rousseau', 'Anouk', 'anouk.rousseau.64@university.edu', 3, 'visiteur médical médicale', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Leclercq', 'Benoît', 'benoît.leclercq.65@university.edu', 3, 'rédacteur médical médicale', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lebreton', 'Capucine', 'capucine.lebreton.66@university.edu', 3, 'formulateur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rey', 'Laetitia', 'laetitia.rey.67@university.edu', 3, 'modéliste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Alexandre', 'Zacharie', 'zacharie.alexandre.68@university.edu', 3, 'mécanicien marine navigant', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guillet', 'Nicole', 'nicole.guillet.69@university.edu', 4, 'enquêteur privé privée', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gaillard', 'Alix', 'alix.gaillard.70@university.edu', 4, 'moniteur-éducateur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Duval', 'Pauline', 'pauline.duval.71@university.edu', 4, 'conseiller sportif sportive en salle de remise en forme', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rivière', 'Adrienne', 'adrienne.rivière.72@university.edu', 4, 'ingénieur procédés en chimie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Tessier', 'Bertrand', 'bertrand.tessier.73@university.edu', 4, 'ingénieur en chef territorial', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gillet', 'Rémy', 'rémy.gillet.74@university.edu', 4, 'climatologue', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guillon', 'Hortense', 'hortense.guillon.75@university.edu', 4, 'microbiologiste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Andre', 'Nathalie', 'nathalie.andre.76@university.edu', 4, 'tonnelier', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Da Silva', 'Éric', 'éric.da silva.77@university.edu', 4, 'juriste en propriété intellectuelle', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Traore', 'Maggie', 'maggie.traore.78@university.edu', 4, 'ingénieur en aéronautique', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lacroix', 'Théodore', 'théodore.lacroix.79@university.edu', 4, 'responsable achats en chimie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bouvet', 'Élisabeth', 'élisabeth.bouvet.80@university.edu', 4, 'chef de projet sites et sols pollués', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lefort', 'Suzanne', 'suzanne.lefort.81@university.edu', 4, 'animateur du patrimoine', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Leclercq', 'Stéphanie', 'stéphanie.leclercq.82@university.edu', 4, 'conservateur territorial de bibliothèques', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Vaillant', 'Vincent', 'vincent.vaillant.83@university.edu', 4, 'ingénieur du son', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Morvan', 'Marie', 'marie.morvan.84@university.edu', 4, 'ingénieur matériaux', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Louis', 'Nicolas', 'nicolas.louis.85@university.edu', 4, 'aérodynamicien', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamel', 'René', 'rené.hamel.86@university.edu', 4, 'océanologue', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fleury', 'Manon', 'manon.fleury.87@university.edu', 4, 'patron pêcheur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guérin', 'Xavier', 'xavier.guérin.88@university.edu', 4, 'ingénieur textile', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mendès', 'Gilbert', 'gilbert.mendès.89@university.edu', 4, 'inspecteur du permis de conduire et de la sécurité routière', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Millet', 'Aimé', 'aimé.millet.90@university.edu', 5, 'pisteur secouriste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pichon', 'Michelle', 'michelle.pichon.91@university.edu', 5, 'technicien en engins de travaux publics', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Coulon', 'Élodie', 'élodie.coulon.92@university.edu', 5, 'chef de projet packaging', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Faivre', 'Hélène', 'hélène.faivre.93@university.edu', 5, 'chaudronnier', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Parent', 'Charles', 'charles.parent.94@university.edu', 5, 'géologue', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Marty', 'Valentine', 'valentine.marty.95@university.edu', 5, 'ingénieur technico-commercial technico-commerciale en électronique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Renault', 'Roger', 'roger.renault.96@university.edu', 5, 'éclairagiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fernandez', 'Camille', 'camille.fernandez.97@university.edu', 5, 'ingénieur environnement', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lecoq', 'Madeleine', 'madeleine.lecoq.98@university.edu', 5, 'expert en assurances', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pons', 'Agathe', 'agathe.pons.99@university.edu', 5, 'ingénieur RD en énergies renouvelables', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Jacquet', 'Claudine', 'claudine.jacquet.100@university.edu', 5, 'commissaire-priseur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Meunier', 'Bertrand', 'bertrand.meunier.101@university.edu', 5, 'ingénieur en imagerie médicale', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Da Silva', 'Jacques', 'jacques.da silva.102@university.edu', 5, 'salesman', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Picard', 'Émile', 'émile.picard.103@university.edu', 5, 'credit manager', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Launay', 'Agathe', 'agathe.launay.104@university.edu', 5, 'marchandiseur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lefort', 'Océane', 'océane.lefort.105@university.edu', 5, 'styliste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dupuy', 'Gilbert', 'gilbert.dupuy.106@university.edu', 5, 'ingénieur forestier forestière', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Buisson', 'Luce', 'luce.buisson.107@university.edu', 6, 'éducateur canin canine', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Colin', 'Eugène', 'eugène.colin.108@university.edu', 6, 'magistrat', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chauvin', 'Augustin', 'augustin.chauvin.109@university.edu', 6, 'anatomiste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Duhamel', 'Céline', 'céline.duhamel.110@university.edu', 6, 'souffleur de verre', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Ramos', 'Georges', 'georges.ramos.111@university.edu', 6, 'océanologue', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Valette', 'Nicole', 'nicole.valette.112@university.edu', 6, 'statisticien en géomarketing', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Girard', 'Constance', 'constance.girard.113@university.edu', 6, 'agent hydrothermal hydrothermale', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Aubert', 'Olivie', 'olivie.aubert.114@university.edu', 6, 'technicien en automatismes', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Weber', 'Maurice', 'maurice.weber.115@university.edu', 6, 'concepteur designer packaging', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mallet', 'Patrick', 'patrick.mallet.116@university.edu', 6, 'chef de cultures légumières', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schneider', 'Emmanuelle', 'emmanuelle.schneider.117@university.edu', 6, 'professeur de mathématiques ou de physique-chimie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bousquet', 'Sophie', 'sophie.bousquet.118@university.edu', 6, 'directeur d''agence bancaire', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Valentin', 'Astrid', 'astrid.valentin.119@university.edu', 6, 'gardien de la paix', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Samson', 'Marthe', 'marthe.samson.120@university.edu', 6, 'ingénieur radioprotection', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Perrot', 'Laure', 'laure.perrot.121@university.edu', 6, 'infirmier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pottier', 'Capucine', 'capucine.pottier.122@university.edu', 6, 'professeur des écoles des écoles', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Adam', 'Thérèse', 'thérèse.adam.123@university.edu', 6, 'volcanologue', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Leclercq', 'Thibaut', 'thibaut.leclercq.124@university.edu', 6, 'technicien logistique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Blondel', 'Aurore', 'aurore.blondel.125@university.edu', 7, 'web-ergonome', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bernier', 'Dorothée', 'dorothée.bernier.126@university.edu', 7, 'consignataire de navire', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Legrand', 'Hugues', 'hugues.legrand.127@university.edu', 7, 'bottier', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Louis', 'Brigitte', 'brigitte.louis.128@university.edu', 7, 'horticulteur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Techer', 'Valentine', 'valentine.techer.129@university.edu', 7, 'pharmacien dans l''industrie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Renault', 'Philippine', 'philippine.renault.130@university.edu', 7, 'monteur en réseaux de distribution électrique', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mary', 'Camille', 'camille.mary.131@university.edu', 7, 'développeur d''applications mobiles', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bruneau', 'Émilie', 'émilie.bruneau.132@university.edu', 7, 'conservateur du patrimoine', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rivière', 'Aimée', 'aimée.rivière.133@university.edu', 7, 'relieur-doreur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Benoit', 'Georges', 'georges.benoit.134@university.edu', 7, 'caissier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Leroux', 'Hortense', 'hortense.leroux.135@university.edu', 7, 'chef de station de traitement des eaux', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fischer', 'Aimé', 'aimé.fischer.136@university.edu', 7, 'ingénieur forage', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Blondel', 'Antoine', 'antoine.blondel.137@university.edu', 7, 'consultant en management de l''innovation', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamel', 'Diane', 'diane.hamel.138@university.edu', 7, 'technicien biologiste', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guérin', 'Madeleine', 'madeleine.guérin.139@university.edu', 7, 'sommelier', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gillet', 'Élisabeth', 'élisabeth.gillet.140@university.edu', 7, 'ingénieur textile', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hoarau', 'Marc', 'marc.hoarau.141@university.edu', 7, 'audioprothésiste', 'Vacataire');
