-- Professeurs
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hubert', 'Catherine', 'catherine.hubert.1@university.edu', 1, 'géophysicien', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Julien', 'Daniel', 'daniel.julien.2@university.edu', 1, 'conducteur de ligne de production alimentaire', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Louis', 'Victoire', 'victoire.louis.3@university.edu', 1, 'hôtesse de l''air', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pelletier', 'Laure', 'laure.pelletier.4@university.edu', 1, 'opticien-lunetier', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guyot', 'Lucie', 'lucie.guyot.5@university.edu', 1, 'éducateur technique spécialisé technique spécialisée', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hervé', 'Lucy', 'lucy.hervé.6@university.edu', 1, 'dépanneur en électroménager', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Couturier', 'Nathalie', 'nathalie.couturier.7@university.edu', 1, 'dépanneur en électroménager', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pages', 'Olivie', 'olivie.pages.8@university.edu', 1, 'guichetier', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Sauvage', 'Sylvie', 'sylvie.sauvage.9@university.edu', 1, 'teinturier blanchisseur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bodin', 'Jacqueline', 'jacqueline.bodin.10@university.edu', 1, 'chargé de recherche et développement déchets', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Giraud', 'Thérèse', 'thérèse.giraud.11@university.edu', 1, 'chef de rayon', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Costa', 'Océane', 'océane.costa.12@university.edu', 1, 'brodeur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rey', 'Luce', 'luce.rey.13@university.edu', 1, 'soigneur d''animaux', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Thibault', 'Emmanuelle', 'emmanuelle.thibault.14@university.edu', 1, 'inspecteur de banque', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lopez', 'Alain', 'alain.lopez.15@university.edu', 1, 'ingénieur process aval', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bourdon', 'Arthur', 'arthur.bourdon.16@university.edu', 1, 'technicien en métrologie', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Olivier', 'Maryse', 'maryse.olivier.17@university.edu', 1, 'architecte', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Poirier', 'Éric', 'éric.poirier.18@university.edu', 1, 'responsable de formation', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Adam', 'Thibaut', 'thibaut.adam.19@university.edu', 1, 'consultant en validation', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Maury', 'Bernard', 'bernard.maury.20@university.edu', 1, 'ingénieur en production et expérimentations végétales', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rey', 'Thibaut', 'thibaut.rey.21@university.edu', 1, 'animalier de laboratoire', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Voisin', 'Thibault', 'thibault.voisin.22@university.edu', 2, 'agent de développement des énergies renouvelables', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Loiseau', 'Lucas', 'lucas.loiseau.23@university.edu', 2, 'ingénieur technico-commercial technico-commerciale en informatique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chrétien', 'Sébastien', 'sébastien.chrétien.24@university.edu', 2, 'ingénieur en fonderie', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('François', 'Clémence', 'clémence.françois.25@university.edu', 2, 'mandataire judiciaire', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Étienne', 'Margaret', 'margaret.étienne.26@university.edu', 2, 'responsable e-CRM', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('François', 'Catherine', 'catherine.françois.27@university.edu', 2, 'juriste droit de l''environnement', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Muller', 'Nath', 'nath.muller.28@university.edu', 2, 'technicien d''intervention clientèle gaz', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gallet', 'Frédérique', 'frédérique.gallet.29@university.edu', 2, 'chargé d''affaires en génie climatique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Millet', 'Patrick', 'patrick.millet.30@university.edu', 2, 'météorologiste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lefèvre', 'Michèle', 'michèle.lefèvre.31@university.edu', 2, 'cadreur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Denis', 'Brigitte', 'brigitte.denis.32@university.edu', 2, 'programmiste', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gosselin', 'Camille', 'camille.gosselin.33@university.edu', 2, 'guichetier', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lopes', 'Thibault', 'thibault.lopes.34@university.edu', 2, 'cordiste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Delmas', 'Célina', 'célina.delmas.35@university.edu', 2, 'musicien', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Godard', 'Philippe', 'philippe.godard.36@university.edu', 2, 'accessoiriste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Legendre', 'Michelle', 'michelle.legendre.37@university.edu', 2, 'chef de projet web/mobile', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Renard', 'Pénélope', 'pénélope.renard.38@university.edu', 2, 'acheteur d''espaces publicitaires', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pruvost', 'Laetitia', 'laetitia.pruvost.39@university.edu', 2, 'convoyeur de fonds', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Maury', 'Jérôme', 'jérôme.maury.40@university.edu', 2, 'designer sonore', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Girard', 'Agnès', 'agnès.girard.41@university.edu', 2, 'ingénieur maintenance aéronautique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schmitt', 'Luce', 'luce.schmitt.42@university.edu', 2, 'responsable de scierie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Meyer', 'Édith', 'édith.meyer.43@university.edu', 2, 'responsable achats en chimie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Salmon', 'Frédérique', 'frédérique.salmon.44@university.edu', 3, 'coiffeur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Perez', 'Zoé', 'zoé.perez.45@university.edu', 3, 'militaire technicien de l''air (MTA)', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Étienne', 'Éléonore', 'éléonore.étienne.46@university.edu', 3, 'médiateur scientifique', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Garcia', 'Joséphine', 'joséphine.garcia.47@university.edu', 3, 'ergonome', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Marion', 'Édith', 'édith.marion.48@university.edu', 3, 'ingénieur qualité moteur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mercier', 'Nicolas', 'nicolas.mercier.49@university.edu', 3, 'chef de chantier en installations électriques', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Legendre', 'Gérard', 'gérard.legendre.50@university.edu', 3, 'cartographe', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bonnet', 'Marguerite', 'marguerite.bonnet.51@university.edu', 3, 'hydrogéologue', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mace', 'Émile', 'émile.mace.52@university.edu', 3, 'océanologue', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pons', 'Noël', 'noël.pons.53@university.edu', 3, 'géothermicien', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Camus', 'Isaac', 'isaac.camus.54@university.edu', 3, 'secrétaire administratif', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Poulain', 'Tristan', 'tristan.poulain.55@university.edu', 3, 'régleur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Blondel', 'Benjamin', 'benjamin.blondel.56@university.edu', 3, 'vitrailliste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bailly', 'Simone', 'simone.bailly.57@university.edu', 3, 'inséminateur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chauvin', 'Anouk', 'anouk.chauvin.58@university.edu', 3, 'consultant en systèmes d''information', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Simon', 'Julie', 'julie.simon.59@university.edu', 3, 'sommelier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Toussaint', 'Olivie', 'olivie.toussaint.60@university.edu', 3, 'entraîneur de chevaux', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bousquet', 'Nath', 'nath.bousquet.61@university.edu', 3, 'ingénieur recherche et développement (R&amp;D) en agroéquipement', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Berthelot', 'Mathilde', 'mathilde.berthelot.62@university.edu', 4, 'hydraulicien', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gaudin', 'Daniel', 'daniel.gaudin.63@university.edu', 4, 'expert-comptable', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bourgeois', 'Alex', 'alex.bourgeois.64@university.edu', 4, 'restaurateur d''oeuvres d''art', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rodrigues', 'Laurence', 'laurence.rodrigues.65@university.edu', 4, 'consultant en conduite de changement', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Garcia', 'Monique', 'monique.garcia.66@university.edu', 4, 'statisticien en analyse sensorielle', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Godard', 'Gabriel', 'gabriel.godard.67@university.edu', 4, 'ingénieur analyste de l''air', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Robert', 'Denise', 'denise.robert.68@university.edu', 4, 'linguiste', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Le Gall', 'Honoré', 'honoré.le gall.69@university.edu', 4, 'facteur d''instruments', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dufour', 'Chantal', 'chantal.dufour.70@university.edu', 4, 'astrophysicien', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Philippe', 'William', 'william.philippe.71@university.edu', 4, 'ingénieur de la police technique et scientifique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Jacquet', 'Thérèse', 'thérèse.jacquet.72@university.edu', 4, 'étanchéiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('François', 'Virginie', 'virginie.françois.73@university.edu', 4, 'barman', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mace', 'Lucie', 'lucie.mace.74@university.edu', 4, 'secrétaire des affaires étrangères', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Vidal', 'Charlotte', 'charlotte.vidal.75@university.edu', 4, 'chaudronnier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Riou', 'Alain', 'alain.riou.76@university.edu', 4, 'ingénieur opticien opticienne', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rousset', 'Robert', 'robert.rousset.77@university.edu', 4, 'web-ergonome', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Charrier', 'Dominique', 'dominique.charrier.78@university.edu', 5, 'ingénieur mathématicien', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Allain', 'Laurent', 'laurent.allain.79@university.edu', 5, 'juge des enfants', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Regnier', 'Louis', 'louis.regnier.80@university.edu', 5, 'facteur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Auger', 'Marc', 'marc.auger.81@university.edu', 5, 'danseur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mathieu', 'Adélaïde', 'adélaïde.mathieu.82@university.edu', 5, 'gardien de la paix', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bernier', 'Christophe', 'christophe.bernier.83@university.edu', 5, 'mécanicien-réparateur en matériel agricole', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Verdier', 'Aimé', 'aimé.verdier.84@university.edu', 5, 'consultant en solutions intégrées', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Royer', 'Aimé', 'aimé.royer.85@university.edu', 5, 'pharmacien dans l''industrie', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Delannoy', 'Gilles', 'gilles.delannoy.86@university.edu', 5, 'restaurateur d''oeuvres d''art', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Poirier', 'Patrick', 'patrick.poirier.87@university.edu', 5, 'ingénieur technico-commercial technico-commerciale', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Legros', 'Joseph', 'joseph.legros.88@university.edu', 5, 'formateur en informatique', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mathieu', 'Paul', 'paul.mathieu.89@university.edu', 5, 'éducateur sportif sportive', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Labbé', 'Camille', 'camille.labbé.90@university.edu', 5, 'électromécanicien', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mathieu', 'Manon', 'manon.mathieu.91@university.edu', 5, 'ingénieur en mécanique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Camus', 'Marcel', 'marcel.camus.92@university.edu', 5, 'attaché de recherche clinique (ARC)', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guyot', 'Anouk', 'anouk.guyot.93@university.edu', 5, 'parfumeur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Legendre', 'Patricia', 'patricia.legendre.94@university.edu', 5, 'conducteur d''engins de travaux publics', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schneider', 'Brigitte', 'brigitte.schneider.95@university.edu', 5, 'étalagiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lambert', 'Jeannine', 'jeannine.lambert.96@university.edu', 5, 'gestionnaire de données cliniques', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Huet', 'Claude', 'claude.huet.97@university.edu', 5, 'développeur d''applications mobiles', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Diallo', 'Émile', 'émile.diallo.98@university.edu', 5, 'réflexologue', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rossi', 'Gilles', 'gilles.rossi.99@university.edu', 5, 'agent d''escale', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Antoine', 'Charlotte', 'charlotte.antoine.100@university.edu', 6, 'technicien électronicien électronicienne', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Thibault', 'Andrée', 'andrée.thibault.101@university.edu', 6, 'développeur informatique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Menard', 'Brigitte', 'brigitte.menard.102@university.edu', 6, 'expert automobile', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hernandez', 'Alphonse', 'alphonse.hernandez.103@university.edu', 6, 'militaire technicien de l''air (MTA)', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Richard', 'Émilie', 'émilie.richard.104@university.edu', 6, 'chargé d''affaires en génie mécanique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lucas', 'Lorraine', 'lorraine.lucas.105@university.edu', 6, 'responsable approvisionnement', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Boyer', 'Henriette', 'henriette.boyer.106@university.edu', 6, 'technicien plasturgiste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Morin', 'Inès', 'inès.morin.107@university.edu', 6, 'chanteur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Teixeira', 'Xavier', 'xavier.teixeira.108@university.edu', 6, 'sculpteur sur bois', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Le Roux', 'Chantal', 'chantal.le roux.109@university.edu', 6, 'garde (chasse, pêche, littoral, rivière, parcs nationaux)', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dupré', 'Yves', 'yves.dupré.110@university.edu', 6, 'spécialiste des affaires réglementaires en chimie', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hervé', 'Juliette', 'juliette.hervé.111@university.edu', 6, 'orthoprothésiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Duhamel', 'Alex', 'alex.duhamel.112@university.edu', 6, 'généticien', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lopes', 'Patricia', 'patricia.lopes.113@university.edu', 6, 'anatomiste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Laporte', 'Caroline', 'caroline.laporte.114@university.edu', 6, 'podo-orthésiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Couturier', 'Gérard', 'gérard.couturier.115@university.edu', 6, 'technicien thermicien thermicienne', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gérard', 'Maurice', 'maurice.gérard.116@university.edu', 6, 'neurobiologiste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Garcia', 'Margot', 'margot.garcia.117@university.edu', 6, 'ajusteur-monteur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Devaux', 'Marc', 'marc.devaux.118@university.edu', 6, 'agent de transit', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dufour', 'Anastasie', 'anastasie.dufour.119@university.edu', 6, 'ouvrier paysagiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Besson', 'Paul', 'paul.besson.120@university.edu', 7, 'déménageur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guillon', 'Gilles', 'gilles.guillon.121@university.edu', 7, 'teinturier blanchisseur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Blanchard', 'Isabelle', 'isabelle.blanchard.122@university.edu', 7, 'ingénieur en aéronautique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Wagner', 'Gérard', 'gérard.wagner.123@university.edu', 7, 'responsable du service après-vente', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Simon', 'Guillaume', 'guillaume.simon.124@university.edu', 7, 'attaché commercial commerciale', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Peron', 'Lucie', 'lucie.peron.125@university.edu', 7, 'esthéticien-cosméticien', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Leclercq', 'Robert', 'robert.leclercq.126@university.edu', 7, 'assistant en études de prix', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('David', 'Gilles', 'gilles.david.127@university.edu', 7, 'ingénieur structures', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rousset', 'Chantal', 'chantal.rousset.128@university.edu', 7, 'installateur en télécoms', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Raymond', 'Capucine', 'capucine.raymond.129@university.edu', 7, 'monteur-câbleur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Duval', 'Aimé', 'aimé.duval.130@university.edu', 7, 'designer sonore', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lopes', 'Raymond', 'raymond.lopes.131@university.edu', 7, 'professeur des écoles des écoles', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Roger', 'Pénélope', 'pénélope.roger.132@university.edu', 7, 'professeur des écoles des écoles', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Antoine', 'Élise', 'élise.antoine.133@university.edu', 7, 'inspecteur des douanes, des finances publiques ou du travail', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Courtois', 'Julie', 'julie.courtois.134@university.edu', 7, 'informaticien industriel industrielle', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dupuy', 'Julie', 'julie.dupuy.135@university.edu', 7, 'webmestre', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mathieu', 'Matthieu', 'matthieu.mathieu.136@university.edu', 7, 'responsable qualité en agroalimentaire', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Courtois', 'Margot', 'margot.courtois.137@university.edu', 7, 'contrôleur de performance', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dias', 'Jeannine', 'jeannine.dias.138@university.edu', 7, 'administrateur de base de données', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Michel', 'Sébastien', 'sébastien.michel.139@university.edu', 7, 'auxiliaire spécialisé vétérinaire', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Baron', 'Michelle', 'michelle.baron.140@university.edu', 7, 'responsable d''élevage agricole', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bourgeois', 'Luce', 'luce.bourgeois.141@university.edu', 7, 'ajusteur-monteur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Besson', 'Sabine', 'sabine.besson.142@university.edu', 7, 'statisticien en géomarketing', 'Assistant');
