-- Professeurs
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamel', 'Astrid', 'astrid.hamel.1@university.edu', 1, 'charcutier-traiteur', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gérard', 'Claire', 'claire.gérard.2@university.edu', 1, 'ingénieur de recherche (papiers cartons)', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Grégoire', 'Joseph', 'joseph.grégoire.3@university.edu', 1, 'éducateur de jeunes enfants', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dias', 'Antoine', 'antoine.dias.4@university.edu', 1, 'ingénieur études et développement en logiciels de simulation', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gimenez', 'Hélène', 'hélène.gimenez.5@university.edu', 1, 'ingénieur production dans les biotechnologies', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Albert', 'Patrick', 'patrick.albert.6@university.edu', 1, 'officier de la Marine nationale', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lebrun', 'Anaïs', 'anaïs.lebrun.7@university.edu', 1, 'ingénieur nucléaire', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schmitt', 'William', 'william.schmitt.8@university.edu', 1, 'conseiller en assurances', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gomez', 'Jules', 'jules.gomez.9@university.edu', 1, 'ingénieur en automatismes', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Jourdan', 'René', 'rené.jourdan.10@university.edu', 1, 'technicien de maintenance en informatique', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hebert', 'Margaud', 'margaud.hebert.11@university.edu', 1, 'expert en sécurité informatique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Besson', 'Rémy', 'rémy.besson.12@university.edu', 1, 'administrateur de biens', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lefèvre', 'William', 'william.lefèvre.13@university.edu', 1, 'hôte d''accueil', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bigot', 'Inès', 'inès.bigot.14@university.edu', 1, 'technicien de police technique et scientifique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bertin', 'Lucy', 'lucy.bertin.15@university.edu', 1, 'ingénieur traitement de l''image', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Jacquot', 'Julie', 'julie.jacquot.16@university.edu', 1, 'pilote d''hélicoptère', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Payet', 'Susan', 'susan.payet.17@university.edu', 1, 'étanchéiste', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dupuy', 'Nathalie', 'nathalie.dupuy.18@university.edu', 2, 'chef de produit touristique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Petit', 'Bertrand', 'bertrand.petit.19@university.edu', 2, 'chef de projet biodiversité', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('François', 'Adèle', 'adèle.françois.20@university.edu', 2, 'soigneur d''animaux', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Da Costa', 'Thierry', 'thierry.da costa.21@university.edu', 2, 'maître d''hôtel', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Maury', 'Denis', 'denis.maury.22@university.edu', 2, 'responsable de site de traitement des déchets', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Brun', 'Raymond', 'raymond.brun.23@university.edu', 2, 'chef de projet packaging', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Delattre', 'Nathalie', 'nathalie.delattre.24@university.edu', 2, 'généticien', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lemonnier', 'Alice', 'alice.lemonnier.25@university.edu', 2, 'chef de mission humanitaire', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fabre', 'Astrid', 'astrid.fabre.26@university.edu', 2, 'technicien radioprotection', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fouquet', 'Juliette', 'juliette.fouquet.27@university.edu', 2, 'diagnostiqueur immobilier', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guérin', 'Victoire', 'victoire.guérin.28@university.edu', 2, 'responsable de projets culturels', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mercier', 'Alphonse', 'alphonse.mercier.29@university.edu', 2, 'conseiller en assurances', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Valette', 'Jeanne', 'jeanne.valette.30@university.edu', 2, 'hot liner', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fouquet', 'Paulette', 'paulette.fouquet.31@university.edu', 2, 'directeur de restaurant', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guillaume', 'Gilles', 'gilles.guillaume.32@university.edu', 2, 'chargé d''études naturalistes', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Perez', 'Manon', 'manon.perez.33@university.edu', 2, 'chef de chantier', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Vallet', 'Luce', 'luce.vallet.34@university.edu', 2, 'énergéticien', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Royer', 'Catherine', 'catherine.royer.35@university.edu', 3, 'pharmacien', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pottier', 'Andrée', 'andrée.pottier.36@university.edu', 3, 'mécanicien et technicien', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Royer', 'Marcelle', 'marcelle.royer.37@university.edu', 3, 'caissier', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bertrand', 'Lorraine', 'lorraine.bertrand.38@university.edu', 3, 'ingénieur production en aéronautique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Barbier', 'Colette', 'colette.barbier.39@university.edu', 3, 'moniteur d''activités équestres', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Potier', 'Patrick', 'patrick.potier.40@university.edu', 3, 'conducteur opérateur opératrice de scierie', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Royer', 'Claudine', 'claudine.royer.41@university.edu', 3, 'chargé d''études économiques', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schneider', 'Bernadette', 'bernadette.schneider.42@university.edu', 3, 'chercheur en physique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Simon', 'Hortense', 'hortense.simon.43@university.edu', 3, 'ingénieur en construction automobile', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Grenier', 'Susanne', 'susanne.grenier.44@university.edu', 3, 'ingénieur cloud computing', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Deschamps', 'Emmanuel', 'emmanuel.deschamps.45@university.edu', 3, 'collecteur de fonds', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Garnier', 'Michel', 'michel.garnier.46@university.edu', 3, 'gestionnaire de patrimoine', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lagarde', 'Stéphane', 'stéphane.lagarde.47@university.edu', 3, 'sapeur-pompier', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Carpentier', 'Alix', 'alix.carpentier.48@university.edu', 3, 'ingénieur en génie climatique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Maillot', 'Bernadette', 'bernadette.maillot.49@university.edu', 3, 'chef de projet démantèlement nucléaire', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Menard', 'Rémy', 'rémy.menard.50@university.edu', 3, 'microtechnicien', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lenoir', 'Caroline', 'caroline.lenoir.51@university.edu', 3, 'formateur en informatique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Raymond', 'Étienne', 'étienne.raymond.52@university.edu', 3, 'ingénieur du son', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Devaux', 'Suzanne', 'suzanne.devaux.53@university.edu', 3, 'climatologue', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Costa', 'Christiane', 'christiane.costa.54@university.edu', 3, 'psychologue', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Normand', 'Daniel', 'daniel.normand.55@university.edu', 3, 'chef de mission humanitaire', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Clerc', 'Olivie', 'olivie.clerc.56@university.edu', 4, 'technicien en engins de travaux publics', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fischer', 'Constance', 'constance.fischer.57@university.edu', 4, 'trader', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Roche', 'Michelle', 'michelle.roche.58@university.edu', 4, 'guide-conférencier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rousseau', 'Henri', 'henri.rousseau.59@university.edu', 4, 'agronome', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Brunet', 'Lucie', 'lucie.brunet.60@university.edu', 4, 'responsable de formation', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mallet', 'Benjamin', 'benjamin.mallet.61@university.edu', 4, 'chef de projet éolien', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bigot', 'Jérôme', 'jérôme.bigot.62@university.edu', 4, 'carreleur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Poulain', 'Martine', 'martine.poulain.63@university.edu', 4, 'animateur nature nature', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pires', 'Madeleine', 'madeleine.pires.64@university.edu', 4, 'secrétaire', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Mace', 'Louise', 'louise.mace.65@university.edu', 4, 'magasinier cariste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Julien', 'Philippe', 'philippe.julien.66@university.edu', 4, 'cartographe', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Valentin', 'Françoise', 'françoise.valentin.67@university.edu', 4, 'rédacteur en chef', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Regnier', 'Honoré', 'honoré.regnier.68@university.edu', 4, 'ingénieur production dans les biotechnologies', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Ferreira', 'Danielle', 'danielle.ferreira.69@university.edu', 4, 'aide-soignant', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Delaunay', 'William', 'william.delaunay.70@university.edu', 4, 'conducteur de bus ou d''autocar', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Verdier', 'Marcelle', 'marcelle.verdier.71@university.edu', 4, 'ingénieur métallurgiste', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Neveu', 'Martine', 'martine.neveu.72@university.edu', 5, 'chargé de pharmacovigilance', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Marchand', 'Maurice', 'maurice.marchand.73@university.edu', 5, 'designer sonore', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Becker', 'Isaac', 'isaac.becker.74@university.edu', 5, 'chef de produit touristique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bonneau', 'Rémy', 'rémy.bonneau.75@university.edu', 5, 'chanteur', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Roy', 'Laetitia', 'laetitia.roy.76@university.edu', 5, 'conducteur d''engins forestiers de récolte en entreprises de travaux forestiers', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guillou', 'Dominique', 'dominique.guillou.77@university.edu', 5, 'statisticien', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Martinez', 'Denis', 'denis.martinez.78@university.edu', 5, 'officier de l''armée de l''air', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Langlois', 'Lucy', 'lucy.langlois.79@university.edu', 5, 'bijoutier-joaillier', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Collin', 'Geneviève', 'geneviève.collin.80@university.edu', 5, 'gestionnaire de contrats informatiques', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Étienne', 'Honoré', 'honoré.étienne.81@university.edu', 5, 'auxiliaire de puériculture', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hoarau', 'Éléonore', 'éléonore.hoarau.82@university.edu', 5, 'médecin humanitaire', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Auger', 'Guillaume', 'guillaume.auger.83@university.edu', 5, 'électromécanicien en remontées mécaniques', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rocher', 'Pauline', 'pauline.rocher.84@university.edu', 5, 'océanologue', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Tanguy', 'Joséphine', 'joséphine.tanguy.85@university.edu', 5, 'ingénieur de recherche clinique et épidémiologique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Leblanc', 'Thibault', 'thibault.leblanc.86@university.edu', 5, 'enseignant spécialisé spécialisée', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Blondel', 'Émile', 'émile.blondel.87@university.edu', 5, 'ingénieur efficacité énergétique du bâtiment', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gonzalez', 'Maggie', 'maggie.gonzalez.88@university.edu', 5, 'chef de projet multimédia', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Grenier', 'Zoé', 'zoé.grenier.89@university.edu', 5, 'halieute', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamon', 'Paulette', 'paulette.hamon.90@university.edu', 6, 'commissaire de police', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Dupré', 'Christine', 'christine.dupré.91@university.edu', 6, 'monteur en réseaux de distribution électrique', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rolland', 'Dorothée', 'dorothée.rolland.92@university.edu', 6, 'solier-moquettiste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Ramos', 'Georges', 'georges.ramos.93@university.edu', 6, 'ingénieur systèmes embarqués', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('De Oliveira', 'Caroline', 'caroline.de oliveira.94@university.edu', 6, 'directeur d''office de tourisme', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pruvost', 'Anastasie', 'anastasie.pruvost.95@university.edu', 6, 'puériculteur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Rémy', 'Xavier', 'xavier.rémy.96@university.edu', 6, 'animateur du patrimoine', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Michaud', 'Clémence', 'clémence.michaud.97@university.edu', 6, 'vendeur conseil caviste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Samson', 'Stéphanie', 'stéphanie.samson.98@university.edu', 6, 'pilote de ligne automatisée (chimie - agroalimentaire - industrie pharmaceutique)', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Petitjean', 'Nath', 'nath.petitjean.99@university.edu', 6, 'opticien-lunetier', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Neveu', 'Franck', 'franck.neveu.100@university.edu', 6, 'ingénieur concepteur conceptrice en mécanique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fleury', 'Audrey', 'audrey.fleury.101@university.edu', 6, 'architecte web', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lucas', 'Monique', 'monique.lucas.102@university.edu', 6, 'ingénieur RD en énergies renouvelables', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Schmitt', 'Yves', 'yves.schmitt.103@university.edu', 6, 'technicien démonstrateur démonstratrice en matériel agricole', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Girard', 'Aurélie', 'aurélie.girard.104@university.edu', 6, 'charcutier-traiteur', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamon', 'Jacqueline', 'jacqueline.hamon.105@university.edu', 6, 'ingénieur réservoir', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fabre', 'Gérard', 'gérard.fabre.106@university.edu', 6, 'mouleur-noyauteur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Pereira', 'André', 'andré.pereira.107@university.edu', 6, 'prothésiste dentaire', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Hamon', 'Étienne', 'étienne.hamon.108@university.edu', 6, 'technicien d''exploitation de l''eau', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Laporte', 'Luce', 'luce.laporte.109@university.edu', 6, 'chef de projet web/mobile', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Fabre', 'Nath', 'nath.fabre.110@university.edu', 7, 'consultant informatique', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Barre', 'Danielle', 'danielle.barre.111@university.edu', 7, 'ergothérapeute', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Marion', 'Zoé', 'zoé.marion.112@university.edu', 7, 'contrôleur des douanes et droits indirects', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lopez', 'Jacqueline', 'jacqueline.lopez.113@university.edu', 7, 'électromécanicien en remontées mécaniques', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lemaire', 'Louis', 'louis.lemaire.114@university.edu', 7, 'expert en sécurité informatique', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gaillard', 'Lucie', 'lucie.gaillard.115@university.edu', 7, 'fiscaliste', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gaillard', 'Timothée', 'timothée.gaillard.116@university.edu', 7, 'technicien de la circulation ferroviaire SNCF', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Gilles', 'Georges', 'georges.gilles.117@university.edu', 7, 'chargé de production', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Renault', 'Jacques', 'jacques.renault.118@university.edu', 7, 'matelot de la marine marchande', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Roche', 'Isaac', 'isaac.roche.119@university.edu', 7, 'conseiller agricole', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guillou', 'Aurore', 'aurore.guillou.120@university.edu', 7, 'gestionnaire de données cliniques', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Garcia', 'Thérèse', 'thérèse.garcia.121@university.edu', 7, 'optronicien', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Lecoq', 'Louis', 'louis.lecoq.122@university.edu', 7, 'iconographe', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Collin', 'Denis', 'denis.collin.123@university.edu', 7, 'responsable de réseau eau potable', 'Maitre de conférences');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Charpentier', 'Colette', 'colette.charpentier.124@university.edu', 7, 'adjoint administratif administrative', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Joly', 'Benjamin', 'benjamin.joly.125@university.edu', 7, 'chocolatier-confiseur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Guibert', 'Nicolas', 'nicolas.guibert.126@university.edu', 7, 'animateur de bassin versant', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Bazin', 'Denise', 'denise.bazin.127@university.edu', 7, 'ingénieur d''application', 'Vacataire');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Faivre', 'Julien', 'julien.faivre.128@university.edu', 7, 'éditeur', 'Professeur');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Chauveau', 'William', 'william.chauveau.129@university.edu', 7, 'ingénieur système', 'Assistant');
INSERT INTO professeurs (nom, prenom, email, dept_id, specialite, grade) VALUES ('Sanchez', 'Célina', 'célina.sanchez.130@university.edu', 7, 'bottier', 'Assistant');
